### ISSUE TITLE
Error: Window is Not Defined

### ISSUE THREAD

**Issue by luisaugusto** [CWFriends/CodeWithFriends#9]
**Describe the Bug**
There is an error when running `npm run generate`:

3:44:33 PM: [error] window is not defined
3:44:33 PM:   at a.setWidths (pages/events/_event/index.js:7128:7)
3:44:33 PM:   at un.run (node_modules/vue/dist/vue.runtime.common.prod.js:6:27543)
3:44:33 PM:   at sn (node_modules/vue/dist/vue.runtime.common.prod.js:6:25554)
3:44:33 PM:   at Array.<anonymous> (node_modules/vue/dist/vue.runtime.common.prod.js:6:12260)
3:44:33 PM:   at Wt (node_modules/vue/dist/vue.runtime.common.prod.js:6:11661)
3:44:33 PM:   at runNextTicks (internal/process/task_queues.js:62:5)
3:44:33 PM:   at listOnTimeout (internal/timers.js:518:9)
3:44:33 PM:   at processTimers (internal/timers.js:492:7)

**Steps to Reproduce**
Run `npm run generate`

**Expected Behavior**
There should be no errors

This can be viewed in the latest [deploy log](https://app.netlify.com/sites/code-with-friends/deploys/5f98a25efe4fc800073d210b)

**Comment by luisaugusto** [comment]
This is an issue with Vuetify, waiting for a pull request to be approved - https://github.com/vuetifyjs/vuetify/pull/12571

**Comment by luisaugusto** [comment]
Now referenced in this PR - https://github.com/vuetifyjs/vuetify/pull/12937
